#!/usr/bin/env bash

# Get useful global variables
. "/home/$USER/dotfiles/installation/globals"

# Get helper functions
. "/home/$USER/dotfiles/installation/functions"

demarcate "INSTALLING PACKAGES"

packages=( "bat" "git" "curl" "stow" "eza" "fzf" "ripgrep" "tmux" "gum" )

if [[ $OS_UBUNTU = 0 ]]; then
	echo "Installing packages in Ubuntu"

	sudo apt update

	# Install common packages
	for package in "${packages[@]}"; do
		yes | sudo apt install libssl-dev
	done

	yes | sudo apt install libssl-dev

	# Install charmbracelet gum
	sudo mkdir -p /etc/apt/keyrings
	curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
	echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list

	# Install eza
	yes | sudo apt install gpg
	sudo mkdir -p /etc/apt/keyrings
	wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
	echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
	sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list

	# Install gh cli
	gh_install

	# Install prequisites for neovim to build from source
	yes | sudo apt-get install ninja-build gettext cmake unzip curl

elif [[ $OS_ARCH = 0 ]]; then
	echo "Installing packages for Arch Linux"
	
	sudo pacman -Syu

	for package in "${packages[@]}"; do
		yes | sudo pacman -S "$package"
	done

	yes | sudo pacman -S github-cli
	yes | sudo pacman -S inetutils
	yes | sudo pacman -S brightnessctl
	yes | sudo pacman -S hyprpaper
	yes | sudo pacman -S pavucontrol
	yes | sudo pacman -S networkmanager
	yes | sudo pacman -S networkmanager-dmenu

	# Install prequisites for neovim to build from source
	yes | sudo pacman -S base-devel cmake unzip ninja curl
fi

# Update tldr doc repository
tldr -u
