#!/usr/bin/env bash

. "~/dotfiles/installation/functions"

demarcate "INSTALLING NVM AND NODE LTS"

# Install nvm and LTS of node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "node" > "~/.nvm/.nvmrc"

nvm install --lts

exec bash 
